### PR TITLE
add pushsafer.com notification service

### PR DESCRIPTION
**Pull request by appzer**

### CODE REVIEW

**Comment by jpmens** [comment]
Merged, thank you!

**Comment by flexiti** [comment]
@appzer 
 Do you know what means ?  (Which means "test", and whether it's a good service because I have not heard of him)

> test Pushsafer for free now

**Comment by appzer** [comment]
@flexiti 
yes its good service with a huge message api.
You can set up your notification by changeing icon, sound, vibration, add URLs and URL schemes, add up to 3 images and many more.

**Comment by sumnerboy12** [comment]
And it is a free service? No message limit?

**Comment by appzer** [comment]
you have a free start quota for each registered device. After that you have to buy api calls.

**Comment by sumnerboy12** [comment]
I struggled to find details of the on going costs on the web site. Can you share a link?

**Comment by appzer** [comment]
at the bottom: https://www.pushsafer.com/en/howto

**Pull request merged**
