### PR TITLE
pass the section name to filter functions

### PR DESCRIPTION
**Pull request by rgitzel**
See https://github.com/jpmens/mqttwarn/issues/327

### CODE REVIEW

**Comment by jpmens** [comment]
This looks very good to me, thank you.

@robdejonge Could you please test this to see if it works for you?

**Comment by robdejonge** [comment]
After installing the `mqttwarn` of the pull request, custom functions called with the `filter` property do not seem to yield the same results. 

Example : 
before the change : 

```
[2018-09-12 07:03:35,697 DEBUG [mqttwarn] Message received on places/home/winecellar/temperature: 14.2
2018-09-12 07:03:35,699 DEBUG [mqttwarn] Section [temperature-stream] matches message on places/home/winecellar/temperature. Processing...
2018-09-12 07:03:35,705 DEBUG [mqttwarn] Filter in section [temperature-stream] has skipped message on places/home/winecellar/temperature](url)
```

after the change : 

```
[](2018-09-12 07:23:33,964 DEBUG [mqttwarn] Message received on places/home/winecellar/temperature: 14.5
2018-09-12 07:23:33,966 DEBUG [mqttwarn] Section [temperature-stream] matches message on places/home/winecellar/temperature. Processing...
2018-09-12 07:23:33,979 DEBUG [mqttwarn] Cannot decode JSON object, payload=14.5: 'float' object has no attribute 'items'
2018-09-12 07:23:33,981 DEBUG [mqttwarn] Message on places/home/winecellar/temperature going to pushover:temperature
2018-09-12 07:23:33,982 DEBUG [mqttwarn] New `pushover:temperature' job: places/home/winecellar/temperature
2018-09-12 07:23:33,985 DEBUG [mqttwarn] Processor #0 is handling: `pushover' for temperature
2018-09-12 07:23:33,990 DEBUG [pushover] *** MODULE=services/pushover.pyc: service=pushover, target=temperature
2018-09-12 07:23:33,992 DEBUG [pushover] Sending pushover notification to temperature [{'sound': 'iPhoneX', 'retry': 60, 'title': 'Temperature reading', 'priority': 0, 'expire': 3600, 'message': 'Winecellar: 14.5 \xc2\xb0C'}]....
2018-09-12 07:23:34,010 DEBUG [connectionpool] Starting new HTTPS connection (1): api.pushover.net:443
2018-09-12 07:23:35,474 DEBUG [connectionpool] https://api.pushover.net:443 "POST /1/messages.json HTTP/1.1" 200 None
2018-09-12 07:23:35,494 DEBUG [pushover] Successfully sent pushover notification
2018-09-12 07:23:35,525 DEBUG [mqttwarn] Job queue has 0 items to process)
```

I did not do any further testing or troubleshooting, because I think the purpose was for existing code to not be impacted by the change. I might be overseeing things (I'm a total novice to all of this), but looks like that objective isn't being met. Let me know if I missed something.

**Comment by rgitzel** [comment]
@robdejonge Can you include the settings from the `.ini` file, and give an example message?  

Did the previous PR work any differently?

**Comment by robdejonge** [comment]
Here is the `.ini` file section: 

```
[temperature-stream]
topic = places/home/+/temperature
alldata = getroom()
filter = togglestate()
targets = pushover:temperature
title = Temperature reading
format = {room}: {payload} {degreesC}
```

The `togglestate` custom function is [here](url
https://github.com/jpmens/mqttwarn/issues/327#issuecomment-419689085).

What I've tested: 

1. Not changing the custom function definition, i.e. leaving it `def togglestate(topic, payload):`, resulted in the custom function being executed but the returned boolean value to not be honored. This is what is shown in my post from a few hours ago. 
2. Changing the custom function to `def togglestate(topic, payload, section, srv):` resulted in the custom function being executed, the section name being passed correctly and the `srv` object allowing direct access to the logging setup. However, here too the returned boolean value is not being honored. 

Does that help?

**Comment by rgitzel** [comment]
@robdejonge I think I've reproduced the problem... boy, talk about learning Python the hard way!  :-p

I should have a fix up soon.

**Comment by rgitzel** [comment]
@robdejonge well that's embarrassing: I changed a variable name, and of course Python didn't care.

Give it a go, now.

**Comment by robdejonge** [comment]
@rgitzel Works in both scenarios! Keeping the original (legacy) version of custom filter functions called with only `topic` and `payload` parameters, it worked just fine. Then adjusted my function to include the `section` and `srv` parameters, and it worked too! Thanks very much for making the change to the code to support this.

**Comment by jpmens** [comment]
Merged. Thank you, @rgitzel for your contribution, and @robdejonge for testing. Much appreciated.

**Pull request merged**
