### PR TITLE
Add feature "dynamic topic targets"

### PR DESCRIPTION
**Pull request by amotl**
Dear Jan-Piet and Ben,

first things first: Thanks for sharing this great project!

We tried to enhance _mqttwarn_ to add functionality we need for our Hiveeyes bee monitoring project. The feature was implemented as generic as possible to provide added value to the _mqttwarn_ infrastructure in general. Kudos go to @einsiedlerkrebs for conceiving it and making this possible.

A short overview over the changes made:
- Interpolate transformation data into topic targets
- Improve overall robustness and address #27, this was essential for implementing the feature

Please get back to us if you have further questions or suggestions.

With kind regards,
Andreas.

### CODE REVIEW

**Comment by einsiedlerkrebs** [comment]
We also updated the appropriate Wiki page. Unfortunately GitHub can not issue pull requests to Wikis, so we link to a PR issued to a clone: #blubb

Cheers,
Richard.

**Comment by jpmens** [comment]
This basically looks very good, however it crashes mqttwarn if I publish a non-JSON payload to your example.

```
2016-02-15 11:50:49,750 DEBUG [mqttwarn] Section [topic-targets-dynamic] matches message on test/topic-targets-dynamic. Processing...
2016-02-15 11:50:49,750 WARNING [mqttwarn] Cannot decode JSON object, payload=blub: No JSON object could be decoded
Traceback (most recent call last):
  File "./mqttwarn.py", line 970, in <module>
    connect()
  File "./mqttwarn.py", line 930, in connect
    mqttc.loop_forever()
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1212, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 792, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1043, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1425, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1881, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2009, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2165, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "./mqttwarn.py", line 532, in on_message
    send_to_targets(section, topic, payload)
  File "./mqttwarn.py", line 586, in send_to_targets
    targetlist = [t.format(**data) for t in targetlist]
KeyError: u'loglevel'
```

Could you address that please?

**Comment by jpmens** [comment]
@einsiedlerkrebs Thanks for the documentation which I have "merged" ;-)

**Comment by amotl** [comment]
Sorry for missing that detail, would have been easy to catch, but it was late. :-) Will have a look and send a fix tonight.

**Comment by jpmens** [comment]
Nur Döner macht schöner! Merged, Danke!

**Comment by amotl** [comment]
Thanks a bunch!

**Pull request merged**
