### PR TITLE
influxdb: make use of https

### PR DESCRIPTION
**Pull request by dkeipp**
Added config option or influxdb plugin "infxproto" to chose http or https.
default value is https to ensure backward compatibility.

### CODE REVIEW

**Comment by jpmens** [comment]
Merged, thank you.

**Comment by amotl** [comment]
Dear @dkeipp,

thanks for your contribution. I have a minor nit to address here: Could we rename `infxproto` to `scheme` here? I believe the former sounds a bit awkward.

With kind regards,
Andreas.

**Comment by dkeipp** [comment]
> Dear @dkeipp,
> 
> thanks for your contribution. I have a minor nit to address here: Could we rename `infxproto` to `scheme` here? I believe the former sounds a bit awkward.
> 
> With kind regards,
> Andreas.

I have no problem to rename this parameter. I chose 'infxproto' because 'protocol' is used by the mqtt client section. This may cause misunderstandings among users.
Now the pull request is merged, and in my opinion we shouldnt change the parameter name.

Regards
Dennis

**Comment by amotl** [comment]
Hi Dennis,

I took the chance that this has not settled within a release to apply the renaming as outlined above. After that, I've released `mqttwarn-0.16.2` so your improvements to the module should now be also available from PyPI.

Thanks again!

With kind regards,
Andreas.

**Pull request merged**
