### PR TITLE
Created a Cloudflare DNS updating service

### PR DESCRIPTION
**Pull request by psyciknz**
Using the publish_public_ip from samplefuncs.py which posts an IP address of your network, you can then update your cloudflare A record dns entries.  Kind of a replacement to DynDNS or Noip services.

I did originally have python 3.7 set, and it recommended that some of the MQTTwarn.py Exceptions change from:
```
Exception exception, ex:
```
to
```
Exception exception as ex:
```
So that is why that is altered.

### CODE REVIEW

**Comment by jpmens** [comment]
Thanks for your contribution. Before I review this, would you please explain what the use case is, in particular as you'll be using builtin `publish_public_ip_address()` to obtain the IP address which you then submit to Cloudflare? At least that's what I'm understanding.

Why would I need this mqttwarn service?

**Comment by psyciknz** [comment]
Basically it's a poor mans dynamic DNS service.  Ie if you use noip and use their free account (which has an 30 day expiration), or dyndns, which is being shut down, this is a replacement for that.

It just seemed a logical place for me to do it, rather than writing something else controlled by openhab/homeassistant to drive the cloudflare api changes to assign an ip address to a dns entry.

**Comment by rgitzel** [comment]
You could accomplish the same thing with a shell script and a cron job?  How does using MQTT help?

**Comment by psyciknz** [comment]
> You could accomplish the same thing with a shell script and a cron job? How does using MQTT help?

It doesn't do it any better or worse....and yes you could do it with cron + shell.  But then you have configuration stuff all over the place.  Where this means most of my external connectivity to outside services are limited to mqttwarn.  Just makes your system (IMO) more self contained.

**Comment by psyciknz** [comment]
So.....maybe this is a case where it needs to be a "personal" service, and we need to further the options for bundled services and ones that users can add, ie a separate directory that can load custom services?

https://github.com/jpmens/mqttwarn/issues/344

**Comment by jpmens** [comment]
I think you're on the right track with us needing a method of providing for "personal" services. This is possible today of course, by dropping the service and its requirements into the `services/` directory.

As to this particular example I don't see widespread use for it. While you did trigger my interest by using the magic incantation (`"dns"` :-) ) it's not something I think we should provide in a default install.

**Comment by psyciknz** [comment]
Ok I’ll close.   Regarding doing local do we want to discuss that?

I know with docker I can just expose the services folder and introduce whatever I want.

But I was wondering about loading modules from services.   Ie built in.  And another folder services.local where users can put their own service files.  I actually already have two, this cloudflare one and an dns gateway that I use.

Equally I can just clone the directory and introduce them before building the docker container.   But I prefer the two folders method as cleaner.

**Comment by psyciknz** [comment]
Cancelled.

**Comment by amotl** [comment]
Hi again,

thank you for this conversation and contribution. The code here has just been added to the [`mqttwarn-contrib`] project, see also https://github.com/jpmens/mqttwarn/issues/435#issuecomment-864401349.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi David,

your extension is now available within the most recent `mqttwarn-full` Docker image.
```shell
docker pull ghcr.io/jpmens/mqttwarn-full:0.26.0

docker run -it --rm \
    ghcr.io/jpmens/mqttwarn-full:0.26.0 \
    python -c "import mqttwarn_contrib.services.cloudflare_zone as plugin; print(plugin.__author__)"
```

With kind regards,
Andreas.

**Pull request closed without merging**
