### PR TITLE
Add rrdtool service

### PR DESCRIPTION
**Pull request by devsaurus**
This plugin simply forwards values to an [rrdtool](http://oss.oetiker.ch/rrdtool/) database.

### CODE REVIEW

**Comment by jpmens** [comment]
Merged, thanks!

**Comment by devsaurus** [comment]
You're welcome - Tanks a lot for this great tool!
Should I update the Wiki with the doc for rrdtool?

**Comment by jpmens** [comment]
> Should I update the Wiki with the doc for rrdtool?

That would be great, thanks.

**Comment by devsaurus** [comment]
Done.

**Pull request merged**
