### PR TITLE
Improve documentation and `setup.py` for `osxnotify` service plugin

### PR DESCRIPTION
**Pull request by amotl**
A small patch to improve the documentation and setup convenience around the `osxnotify` rework.

/cc @portalzine

### CODE REVIEW

**Review by jpmens — APPROVED** [review]

**Comment by portalzine** [comment]
Was thinking about proposing another documentation update as well, but wanted to stick with the original. Might be worth moving the plugin to a new name in the future, like "desktopnotify". Thanks for the update.

**Comment by jpmens** [comment]
I second the name change to `desktopnotify` in order to remove the inaccurate operating system denomination from the current name.

**Comment by amotl** [comment]
I totally agree with the name change. However, I am proposing to call the service just `desktop.py`. I think the "notify" suffix is somehow redundant in this context. Let me know what you think about it. In any case, I can submit a corresponding patch.

**Comment by portalzine** [comment]
I agree,  "..notify" is a bit redundant, so desktop.py works 👍

**Comment by jpmens** [comment]
I feel `desktop` is too generic as we might have other notifiers for desktops. :)

**Comment by portalzine** [comment]
toast , bubble or popup_notifier

**Comment by amotl** [comment]
> I second the name change to `desktopnotify` [...] and feel `desktop` is too generic.

I am also fine with that decision. Let's just do it like that.

**Pull request merged**
