### PR TITLE
Begin adding software tests for service plugins

### PR DESCRIPTION
**Pull request by amotl**
Hi there,

this patch starts adding software tests for all service plugins.

The tests will not be integration tests, all domain-specific outbound calls or libraries will be mocked instead. Modulo that detail, we aim for 100% test coverage. More work will have to go into this endeavor, currently only 11% of all plugins are being tested.

While adding some tests, minor issues with individual service plugins have been fixed. At the same time, this patch drops official support for Python 2.

With kind regards,
Andreas.

### CODE REVIEW

**Comment by jpmens** [comment]
Great we're dropping Python 2; I welcome that. :-)

**Comment by amotl** [comment]
Let's integrate it to make it easier for @psyciknz to work with this improvements, see https://github.com/jpmens/mqttwarn/issues/526#issuecomment-863649072 ff.

**Comment by amotl** [comment]
> I will try to continue working on this topic after vacation.

Let me know if you want to bring this in beforehand. I would also cut a new release immediately after.

**Review by jpmens — APPROVED** [review]
LGTM

**Pull request merged**
