### PR TITLE
Accept key pair defined in config file instead of user/password

### PR DESCRIPTION
**Pull request by DavidVentura**

### CODE REVIEW

**Comment by jpmens** [comment]
You say "Accept key pair defined in config file"; it's not clear to me (README missing) where in mqttwarn's configuration you specify which key to use.

**Comment by DavidVentura** [comment]
You are right. I'll update the README shortly. The idea is that if username and password are both missing from config, the program will read user's ssh config file and load from there:

* Username, keyfile (obligatory)
* Port, hostname (optional)

**Comment by DavidVentura** [comment]
I've updated the README accordingly. Let me know what you think

**Comment by jpmens** [comment]
Merged, thank you.

**Pull request merged**
