### PR TITLE
Fix Docker setup

### PR DESCRIPTION
**Pull request by amotl**
Hi there,

@tg44 made us aware that we have been tripped by unwanted cache hits when building Docker images, thanks again. This patch hopefully mitigates the problem. What do you think, Gergő?

With kind regards,
Andreas.

### CODE REVIEW

**Comment by tg44** [comment]
This seems like a good docker file, the only thing that can be better to move down the copy+install right before the cmd so most of the layers can be reused, but it is really just nitpicking. (moving 10-12 to 30, so from 11 layers we could reuse 8 or so)

**Review by jpmens — APPROVED** [review]
If @tg44 is happy, I am happy. :-)

**Comment by amotl** [comment]
Great. Can you check 0ea8f76d55b5b, @tg44?

**Comment by tg44** [comment]
Seems ok to me!

**Comment by jpmens** [comment]
rabbit-7989

```
Could not install packages due to an OSError: [Errno 13] Permission denied: '/home/mqttwarn'
Check the permissions.
Removing intermediate container e44affdb045a
The command '/bin/sh -c pip install /src' returned a non-zero code: 1
```

**Pull request merged**
