### PR TITLE
[Pushsafer] add new parameter cr, ao, af

### PR DESCRIPTION
**Pull request by appzer**
Adding options to use Pushsafer's [_Confirm_](https://www.pushsafer.com/en/pushapi_ext#API-CR), [_Answer Options_](https://www.pushsafer.com/en/pushapi_ext#API-AO), and [_Force Answer_](https://www.pushsafer.com/en/pushapi_ext#API-AF) features.

### CODE REVIEW

**Comment by amotl** [comment]
Dear Kevin,

thanks a stack for submitting this patch, we appreciate it.

I've rushed to bring in GH-624, in order to take care about backwards compatibility. Independently of this, I found your patch to diverge slightly at [^1], I think this is the reason why it currently does not fit properly.

Can I humbly ask you to take a second look? Now, after rebasing on top of the `main` branch, you can also use the command `pytest --no-cov -k pushsafer` as additional tooling which will hopefully give you reasonable feedback.

With kind regards,
Andreas.

[^1]: https://github.com/appzer/mqttwarn/blob/cba2e32/mqttwarn/services/pushsafer.py#L82-L86

**Comment by amotl** [comment]
Dear Kevin,

at GH-629, I started working on a draft to improve the configuration style for the Pushsafer service plugin. I think it will significantly improve usability and extendability. However, if we bring this in, you will probably need to rework your patch. I hope for your understanding.

With kind regards,
Andreas.

**Comment by appzer** [comment]
Hi @amotl,

i check the issue and will send a new pull request.

Kevin

**Comment by amotl** [comment]
Hi Kevin,

all right, thank you. I think we will only need to bring in the corresponding improvements to the v2-style configuration layout for Pushsafer, as implemented by GH-629.

With kind regards,
Andreas.

**Pull request closed without merging**
