### PR TITLE
new plugin for dashing

### PR DESCRIPTION
**Pull request by kstaniek**
address: "widgets|dashboards", "name|*"
for widgets: 
  message: json string with field accepted by dashboard
for dashboard:
  message: { "action": "reload" } this is the only action implemented in dashing
Sample config:

```
    [config:dashing]
    hostname = 'dashboard.home.local'
    port = 3030
    auth_token = 'YOUR_AUTH_TOKEN'
    timeout = 5
    targets = {
        'outside_temp': [ "widgets", "klimato" ],   # target for specific widget "klimato"
        'widgets': [ "widgets" ],                   # target for widget where last topic part is a widget name
        'dashboards': [ "dashboards", "*" ],        # target for all dashboards
        }
```

### CODE REVIEW

**Comment by jpmens** [comment]
Thanks for this. I need a bit more info.

1. What is 'dashing'?
2. Can you show a screenshot which we include in the docs?
3. Apropos docs: please add documentation (in seperate file if you
   prefer) that we can add to README.md
4. What is the file `statefunctions.py` for?
5. Why is .idea in .gitignore?

Thanks

**Comment by kstaniek** [comment]
1) Dashing is a dashboard engine http://dashing.io
2) The screenshot is maybe not relevant. The idea is just to asynchronously distribute updates to the customised dashboards/widgets through MQTT. 
3) Will prepare the documentation and send later. Need to find some time (few days max)
4) This is my mistake. Can be deleted.
5) .idea is a directory with project metafiles used for the PyCharm IDE. It is a good practice to have it .gitignore for people using this IDE.

**Comment by jpmens** [comment]
@kstaniek Will merge this when README is updated. ;-)

**Comment by brunkj** [comment]
Just curious if this got added?   I use dashing and would love to use this

**Comment by jpmens** [comment]
This is open (unmerged), but as I told @kstaniek, I'll merge when documentation is added.

**Comment by brunkj** [comment]
Roger that!

**Comment by kstaniek** [comment]
Sorry, guys, will update it. I have no spare time so far.

**Comment by jpmens** [comment]
FYI, I'm in a merge mood, but not without documentation. :-)

**Comment by jpmens** [comment]
I'd still like to merge this, but I need documentation in the README please.

**Pull request closed without merging**
